name       : qt5-3d
version    : 5.15.8
release    : 20
source     :
    - git|https://invent.kde.org/qt/qt/qt3d.git : c3c7e6ebc29cce466d954f72f340a257d76b5ec2
homepage   : https://www.qt.io
license    :
    - BSD-3-Clause
    - LGPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt 3D module
description: |
    Qt 3D provides functionality for near-realtime simulation systems with support for 2D and 3D rendering in both Qt C++ and Qt Quick applications.
builddeps  :
    - pkgconfig(Qt5Quick)
    - vulkan-headers
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qt3d.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
