name       : qt5-3d
version    : 5.15.4
release    : 17
source     :
    - git|https://invent.kde.org/qt/qt/qt3d.git : 5fd3906445ac95bf1cca6e7a7e0aeb6e3bcf5016
homepage   : https://www.qt.io
license    :
    - BSD-3-Clause
    - LGPL-3.0-only
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt 3D module
description: |
    Qt 3D provides functionality for near-realtime simulation systems with support for 2D and 3D rendering in both Qt C++ and Qt Quick applications.
builddeps  :
    - pkgconfig(Qt5Quick)
    - vulkan-headers
patterns   :
    - demos :
        - /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qt3d.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
