name       : qt5-3d
version    : 5.13.2
release    : 5
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qt3d-everywhere-src-5.13.2.tar.xz : d1b9fc0be82264b5f76c3a5330901dff95c1f2bcb67916c3fac6bad4ff69adc9
homepage   : https://www.qt.io
license    :
    - BSD-3-Clause
    - LGPL-3.0-only
component  : desktop.qt
summary    : Qt 3D module
description: |
    Qt 3D provides functionality for near-realtime simulation systems with support for 2D and 3D rendering in both Qt C++ and Qt Quick applications.
builddeps  :
    - pkgconfig(Qt5Quick)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
