name       : qt5-3d
version    : 5.12.2
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.2/submodules/qt3d-everywhere-src-5.12.2.tar.xz : d4036e7ac146ba78784dde0dd99e8182372b7c38e832e33b61fed4187de0ad06
license    :
    - BSD-3-Clause
    - LGPL-3.0-only
component  : desktop.qt
summary    : Qt 3D module
description: |
    Qt 3D provides functionality for near-realtime simulation systems with support for 2D and 3D rendering in both Qt C++ and Qt Quick applications.
builddeps  :
    - pkgconfig(Qt5Quick)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
