name       : qt5-3d
version    : 5.12.3
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qt3d-everywhere-src-5.12.3.tar.xz : 8997f07c816bbc6dd43fc2171801178bc65e704d35039998530cfa49837eaa7d
license    :
    - BSD-3-Clause
    - LGPL-3.0-only
component  : desktop.qt
summary    : Qt 3D module
description: |
    Qt 3D provides functionality for near-realtime simulation systems with support for 2D and 3D rendering in both Qt C++ and Qt Quick applications.
builddeps  :
    - pkgconfig(Qt5Quick)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
